CREATE TABLE TEMPLATES (
  TEMPLATE_NAME VARCHAR(255),
  CLOSURE_CLASS VARCHAR(255),
  JAR_FILE VARCHAR(255),
  PRIMARY KEY (TEMPLATE_NAME)
);

CREATE TABLE TEMPLATE_EXECUTION (
	TEMPLATE_ID VARCHAR(255),
  	TEMPLATE_NAME VARCHAR(255),
  	EXECUTION_PARAMS CLOB,
  	EXECUTION_RESULT CLOB,
  	EXECUTION_METRICS CLOB,
  	PRIMARY KEY (TEMPLATE_ID) 	  	
);